version: "3.8"
services:
  db:
    container_name: balakanyna_db
    platform: linux/amd64
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - "./src/db/tmp/data:/var/lib/mysql"
    env_file:
      - ".env"
